# Generated by Django 3.1 on 2021-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedworkout',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('p', 'Pending'), ('d', 'Declined')], default='p', max_length=8),
        ),
    ]
