# Generated by Django 3.1 on 2021-04-12 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggested_workouts', '0002_auto_20210309_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedworkout',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_suggested_workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggestedworkout',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_suggested_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
