# Generated by Django 3.1 on 2021-03-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0002_auto_20210304_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedworkout',
            name='visibility',
            field=models.CharField(default='PU', max_length=8),
        ),
    ]
