# Generated by Django 3.1 on 2021-03-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0003_suggestedworkout_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedworkout',
            name='visibility',
        ),
    ]
