# Generated by Django 3.1 on 2021-03-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0004_remove_suggestedworkout_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedworkout',
            name='visibility',
            field=models.CharField(blank=True, default='', max_length=8, null=True),
        ),
    ]
