# Generated by Django 3.1 on 2021-02-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suggested_workouts', '0005_auto_20210225_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedworkout',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
