# Generated by Django 3.1 on 2021-03-05 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0005_suggestedworkout_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedworkout',
            name='visibility',
        ),
        migrations.DeleteModel(
            name='WorkoutRequest',
        ),
    ]
