# Generated by Django 3.1 on 2021-02-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0006_auto_20210225_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedworkout',
            name='visibility',
        ),
    ]
