# Generated by Django 3.1 on 2021-03-04 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=users.models.athlete_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('p', 'Pending'), ('d', 'Declined')], default='p', max_length=8),
        ),
        migrations.AddField(
            model_name='offer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='OfferResponse',
        ),
        migrations.AddField(
            model_name='athletefile',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athletefile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
