# Generated by Django 3.1 on 2021-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210309_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='RememberMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_me', models.CharField(max_length=500)),
            ],
        ),
    ]
