# Generated by Django 3.1 on 2021-04-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210418_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RememberMe',
        ),
    ]
