# Generated by Django 3.1 on 2020-09-10 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutfile",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workout_files",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
