# Generated by Django 3.1 on 2021-04-18 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210309_1939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RememberMe',
        ),
    ]
