# Generated by Django 3.1 on 2021-03-05 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210304_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_instances', to='workouts.workout'),
        ),
    ]
