# Generated by Django 3.1 on 2021-04-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210418_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='suggested_workout',
        ),
        migrations.RemoveField(
            model_name='exerciseinstance',
            name='workout',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseInstance',
        ),
    ]
