# Generated by Django 3.1 on 2021-02-27 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggested_workouts', '0007_remove_suggestedworkout_visibility'),
        ('workouts', '0004_exerciseinstance_suggested_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutfile',
            name='suggested_workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_workout_files', to='suggested_workouts.suggestedworkout'),
        ),
    ]
